server {
    listen 80;
    server_name tell.guru www.tell.guru;

    root /var/www/html;
    index index.html index.php;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        try_files $uri $uri/ =404;
    }

    location ~ /\.ht {
        deny all;
    }
}
